services:
  mongo:
    container_name: zenity-mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789

  app:
    container_name: zenity-next
    restart: always
    build: app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    environment:
      DB_URI: "mongodb://root:123456789@mongo:27017/admin"

